"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@t)u&geizd8id7dwh$tkilo&yc=h+jk)c17sd8tnrz6w+!)w0m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow all hosts during development (change in production!)
ALLOWED_HOSTS = ["*", "10.147.252.13", "localhost", "127.0.0.1"]
CSRF_TRUSTED_ORIGINS = ["http://10.147.252.13:8000", "http://10.147.252.13:8001", "http://localhost:8000", "http://localhost:8001", "http://127.0.0.1:8000", "http://127.0.0.1:8001"]





# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'rides',
    'locations',
    'rest_framework.authtoken',
]

# Add Channels and Daphne if installed (for WebSocket support)
try:
    import channels
    INSTALLED_APPS.insert(0, 'daphne')
    INSTALLED_APPS.append('channels')
except ImportError:
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'reikeke_db',
        'USER': 'postgres',
        'PASSWORD': 'gemsas',
        'HOST': 'localhost',  
        'PORT': '5432',       
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

# Custom authentication backend for phone_number USERNAME_FIELD
AUTHENTICATION_BACKENDS = [
    'accounts.backends.PhoneNumberBackend',
]

# Channels configuration
ASGI_APPLICATION = 'core.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# CORS Configuration - Allow React Native app to communicate with backend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8081",
    "http://localhost:8082",  # Expo dev server
    "http://localhost:19000",
    "http://localhost:19001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8081",
    "http://127.0.0.1:8082",  # Expo dev server
    "http://127.0.0.1:19000",
    "http://127.0.0.1:19001",
    "http://10.111.187.13:3000",
    "http://10.111.187.13:8081",
    "http://10.111.187.13:8082",  # Expo dev server
    "http://10.111.187.13:19000",
    "http://10.111.187.13:19001",
    "http://10.44.214.13:8000",  # Current dev machine
    "http://10.44.214.13:19000",  # Expo dev server
    "http://10.44.214.13:19001",
    "http://10.147.252.13:8000",  # Current dev machine IP
    "http://10.147.252.13:8081",  # Metro bundler
    "http://10.147.252.13:8082",  # Expo dev server
    "http://10.147.252.13:19000", # Expo dev server
    "http://10.147.252.13:19001", # Expo dev server
    "http://172.26.24.13:8000",  # Previous IP
    "http://172.26.24.13:8081",
    "http://172.26.24.13:8082",  # Expo dev server
    "http://172.26.24.13:19000",
    "http://172.26.24.13:19001",
]

CORS_ALLOW_CREDENTIALS = True

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# Basic logging to console for debugging (show INFO from accounts app)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
