# Generated by Django 5.2.8 on 2025-12-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverLocation',
        ),
    ]
